import { useCallback, useEffect, useMemo, useRef, useState } from 'react'

const C={page:'#F8F6F0',ink:'#22211E',muted:'#65615B',border:'#E0DDD6',blue:'#2660C4',blueTint:'#EAF0FB',blueBorder:'#8AA8DD',purple:'#7B3F9E',purpleTint:'#F3EEFA',purpleBorder:'#C99BE0',green:'#1E7A5E'}
const scenarios={
 car:{tab:'🚗 Car — speed',icon:'🚗',xUnit:'hours',xOne:'1 hour',xMax:4,yUnit:'miles',yMax:240,min:10,max:60,step:10,initial:40,noun:'car',verb:'travels',rateUnit:'miles per hour'},
 tank:{tab:'💧 Tank — filling',icon:'💧',xUnit:'minutes',xOne:'1 minute',xMax:10,yUnit:'liters',yMax:100,min:2,max:10,step:2,initial:6,noun:'tank',verb:'gains',rateUnit:'liters per minute'},
}
const P={l:58,r:24,t:24,b:48},clamp=(v,a,b)=>Math.max(a,Math.min(b,v))

export default function RateOfChangeExplorer(){
 const canvasRef=useRef(),wrapRef=useRef(),rafRef=useRef(),runningRef=useRef(false)
 const [kind,setKind]=useState('car'),[rates,setRates]=useState({car:40,tank:6}),[width,setWidth]=useState(720),[progress,setProgress]=useState(0),[running,setRunning]=useState(false),[complete,setComplete]=useState(false),[ghosts,setGhosts]=useState({car:[],tank:[]})
 const s=scenarios[kind],rate=rates[kind],value=rate*s.xMax*progress
 const stop=useCallback(()=>{cancelAnimationFrame(rafRef.current);runningRef.current=false;setRunning(false)},[])
 useEffect(()=>()=>stop(),[stop])
 useEffect(()=>{const ro=new ResizeObserver(([e])=>setWidth(Math.max(300,Math.floor(e.contentRect.width))));ro.observe(wrapRef.current);return()=>ro.disconnect()},[])
 const reset=useCallback(()=>{stop();setProgress(0);setComplete(false)},[stop])
 const switchScenario=key=>{if(key===kind)return;stop();setKind(key);setProgress(0);setComplete(false)}
 const changeRate=e=>{const next=Number(e.target.value);setRates(old=>({...old,[kind]:next}));setProgress(0);setComplete(false)}
 const go=()=>{if(runningRef.current)return;cancelAnimationFrame(rafRef.current);runningRef.current=true;setRunning(true);setComplete(false);setProgress(0);const start=performance.now(),duration=3200;const tick=now=>{const p=clamp((now-start)/duration,0,1);setProgress(p);if(p<1)rafRef.current=requestAnimationFrame(tick);else{runningRef.current=false;setRunning(false);setComplete(true);setGhosts(old=>({...old,[kind]:[...old[kind].filter(v=>v!==rate),rate].slice(-3)}))}};rafRef.current=requestAnimationFrame(tick)}

 const draw=useCallback(()=>{const el=canvasRef.current;if(!el)return;const h=181,dpr=devicePixelRatio||1;el.width=width*dpr;el.height=h*dpr;el.style.width=width+'px';el.style.height=h+'px';const c=el.getContext('2d');c.setTransform(dpr,0,0,dpr,0,0);c.clearRect(0,0,width,h);const pw=width-P.l-P.r,ph=h-P.t-P.b,x=v=>P.l+v/s.xMax*pw,y=v=>P.t+(1-v/s.yMax)*ph;c.fillStyle='#fff';c.fillRect(0,0,width,h)
  c.font='600 11px Inter,system-ui';c.fillStyle=C.muted;c.textAlign='right';c.textBaseline='middle';for(let i=0;i<=4;i++){const val=s.yMax*i/4,yy=y(val);c.strokeStyle='#E8E4DD';c.lineWidth=1;c.beginPath();c.moveTo(P.l,yy);c.lineTo(width-P.r,yy);c.stroke();c.fillText(String(val),P.l-8,yy)}c.textAlign='center';c.textBaseline='top';for(let i=0;i<=4;i++){const val=s.xMax*i/4;c.fillText(String(val),x(val),h-P.b+8)}c.strokeStyle='#77736D';c.lineWidth=1.2;c.beginPath();c.moveTo(P.l,P.t);c.lineTo(P.l,h-P.b);c.lineTo(width-P.r,h-P.b);c.stroke();c.fillStyle=C.ink;c.font='700 11px Inter,system-ui';c.fillText(s.xUnit,width/2,h-16);c.save();c.translate(14,h/2);c.rotate(-Math.PI/2);c.fillText(s.yUnit,0,0);c.restore()
  ghosts[kind].forEach(g=>{c.strokeStyle='rgba(123,63,158,.18)';c.lineWidth=3;c.beginPath();c.moveTo(x(0),y(0));c.lineTo(x(s.xMax),y(g*s.xMax));c.stroke()})
  const endX=s.xMax*progress,endY=rate*endX;if(progress>0){c.strokeStyle=C.purple;c.lineWidth=4;c.lineCap='round';c.beginPath();c.moveTo(x(0),y(0));c.lineTo(x(endX),y(endY));c.stroke();c.beginPath();c.arc(x(endX),y(endY),6,0,Math.PI*2);c.fillStyle=C.purple;c.fill();c.strokeStyle='#fff';c.lineWidth=2;c.stroke()}
  if(complete){const x0=x(0),x1=x(1),y0=y(0),y1=y(rate);c.lineCap='butt';c.lineWidth=4;c.strokeStyle=C.blue;c.beginPath();c.moveTo(x0,y0);c.lineTo(x1,y0);c.stroke();c.fillStyle=C.blue;c.font='800 11px Inter,system-ui';c.textAlign='center';c.textBaseline='top';c.fillText(s.xOne,(x0+x1)/2,y0+8);c.strokeStyle=C.green;c.beginPath();c.moveTo(x1,y0);c.lineTo(x1,y1);c.stroke();c.fillStyle=C.green;c.textAlign='left';c.textBaseline='middle';c.fillText(`+${rate} ${s.yUnit}`,x1+8,(y0+y1)/2)}
 },[width,s,kind,ghosts,progress,rate,complete]);useEffect(draw,[draw])
 const shownValue=Math.round(value),pct=progress*100
 const hint=useMemo(()=>`Rate of change is how much one thing changes for every 1 unit of another. Here it’s ${s.rateUnit} — and it’s exactly the steepness of the line.${complete?` The triangle shows the rise for a run of just ${s.xOne}.`:''}`,[s,complete])
 return <div className="roc" style={{background:C.page,color:C.ink}}><style>{`.roc{height:500px;overflow:hidden;padding:8px 12px;font-family:Inter,system-ui}.roc *{box-sizing:border-box}.roc-card{background:#fff;border:.5px solid ${C.border};border-radius:12px}.roc-tabs{height:32px;display:flex;gap:8px}.roc-tab{flex:1;border:1px solid ${C.blueBorder};border-radius:9px;padding:5px 10px;background:#fff;color:${C.blue};font-size:12px;font-weight:800;cursor:pointer}.roc-tab[aria-selected=true]{background:${C.blue};color:#fff}.roc-task{height:30px;margin:6px 0;padding:6px 12px;border-radius:8px;background:${C.blueTint};border-left:4px solid ${C.blue};color:${C.blue};font-size:12px;font-weight:700}.roc-live{height:70px;margin-bottom:6px;position:relative;overflow:hidden}.roc-road{position:absolute;left:5%;right:5%;bottom:17px;border-top:3px dashed #AAA49B}.roc-car{position:absolute;bottom:19px;transform:translateX(-50%);font-size:23px}.roc-label{position:absolute;bottom:40px;transform:translateX(-50%);font-size:11px;font-weight:800;color:${C.purple};white-space:nowrap}.roc-tank{position:absolute;left:50%;top:5px;width:58px;height:60px;transform:translateX(-50%);border:3px solid ${C.blue};border-radius:6px 6px 9px 9px;overflow:hidden;background:${C.blueTint}}.roc-water{position:absolute;left:0;right:0;bottom:0;background:${C.purpleBorder};transition:none}.roc-tank-label{position:absolute;left:calc(50% + 42px);top:27px;color:${C.purple};font-size:11px;font-weight:800}.roc-graph{overflow:hidden}.roc canvas{display:block;width:100%}.roc-rate{height:43px;margin-top:5px;padding:5px 11px;background:${C.purpleTint};border-color:${C.purpleBorder};color:${C.purple}}.roc-rate strong{display:block;font-size:17px}.roc-rate span{font-size:11px;font-weight:700}.roc-controls{height:38px;display:grid;grid-template-columns:minmax(220px,1fr) auto auto;gap:8px;align-items:end;margin-top:5px}.roc-slider label{display:flex;justify-content:space-between;font-size:11px;font-weight:800;margin-bottom:1px}.roc-slider input{width:100%;accent-color:${C.purple}}.roc-btn{height:34px;border-radius:9px;padding:5px 13px;font-size:12px;font-weight:800;cursor:pointer}.roc-go{border:1px solid ${C.green};background:${C.green};color:#fff}.roc-reset{border:1px solid ${C.purple};background:#fff;color:${C.purple}}.roc-btn:disabled{opacity:.45;cursor:not-allowed}.roc-hint{height:37px;overflow:hidden;margin-top:5px;padding:5px 9px;font-size:11px;line-height:1.2}.roc-key{height:16px;display:flex;gap:14px;margin:3px 0 0;font-size:10px;color:${C.muted};font-weight:700}.roc-dot{display:inline-block;width:14px;height:3px;margin-right:5px;vertical-align:middle}`}</style>
  <div className="roc-tabs" role="tablist" aria-label="Scenario"><button className="roc-tab" role="tab" aria-selected={kind==='car'} onClick={()=>switchScenario('car')}>🚗 Car — speed</button><button className="roc-tab" role="tab" aria-selected={kind==='tank'} onClick={()=>switchScenario('tank')}>💧 Tank — filling</button></div>
  <div className="roc-task">Set the {kind==='car'?'speed':'fill rate'}, press Go, and watch the graph draw itself. <strong>Steeper line = faster rate.</strong></div>
  <section className="roc-card roc-live" aria-label={kind==='car'?`Car has traveled ${shownValue} miles`:`Tank contains ${shownValue} liters`}>{kind==='car'?<><div className="roc-road"/><div className="roc-label" style={{left:`${5+pct*.9}%`}}>{shownValue} mi</div><div className="roc-car" style={{left:`${5+pct*.9}%`}}>🚗</div></>:<><div className="roc-tank"><div className="roc-water" style={{height:`${pct}%`}}/></div><div className="roc-tank-label">{shownValue} L</div></>}</section>
  <section ref={wrapRef} className="roc-card roc-graph"><canvas ref={canvasRef} role="img" aria-label={`${s.yUnit} by ${s.xUnit} graph. Current rate ${rate} ${s.rateUnit}.`}/></section>
  <div className="roc-key"><span><i className="roc-dot" style={{background:C.purple}}/>current run</span>{ghosts[kind].length>0&&<span><i className="roc-dot" style={{background:'rgba(123,63,158,.25)'}}/>past runs</span>}{complete&&<span>blue = 1-unit run · green = rise</span>}</div>
  <section className="roc-card roc-rate"><strong>{rate} {s.rateUnit}</strong><span>Every 1 {kind==='car'?'hour':'minute'}, the {s.noun} {s.verb} {rate} more {s.yUnit}.</span></section>
  <div className="roc-controls"><div className="roc-slider"><label htmlFor="roc-rate"><span>{kind==='car'?'Speed':'Fill rate'}</span><span>{rate} {kind==='car'?'mph':'L/min'}</span></label><input id="roc-rate" type="range" min={s.min} max={s.max} step={s.step} value={rate} onChange={changeRate} disabled={running}/></div><button className="roc-btn roc-go" type="button" onClick={go} disabled={running}>▶ {running?'Running…':'Go'}</button><button className="roc-btn roc-reset" type="button" onClick={reset}>↺ Reset</button></div>
  <div className="roc-card roc-hint">💡 <strong>Rate of change</strong> {hint.slice('Rate of change'.length)}</div>
 </div>
}
