import { useCallback, useEffect, useMemo, useRef, useState } from 'react'

const C={page:'#F8F6F0',ink:'#20201D',muted:'#66635D',border:'#E0DDD6',teal:'#1E5F74',purple:'#7B3F9E',purpleTint:'#F3EEFA',orange:'#B25A1E',green:'#27500A',greenTint:'#EAF3DE',rose:'#8A2540',roseTint:'#FBE9ED'}
const rounds=[
['🕯️','A candle burns 3 cm each hour','How tall is the candle after each hour?','hours','height (cm)',[24,21,18,15,12,9],1],
['🦠','A bacteria colony doubles','How many groups of bacteria are there?','time steps','groups',[1,2,4,8,16,32],0],
['💰','Saving $5 every week','You start with $10, then save the same amount weekly.','weeks','savings ($)',[15,20,25,30,35,40],1],
['🌱','A square garden grows','Each side grows by 1 m. What happens to its area?','side length (m)','area (m²)',[1,4,9,16,25,36],0],
['🚕','A taxi costs $4 plus $2 per mile','Predict the total fare as the trip gets longer.','miles','fare ($)',[6,8,10,12,14,16],1],
['⚽','A ball falls farther each second','Gravity makes the distance grow faster and faster.','seconds','distance (m)',[5,20,45,80,125,180],0],
].map(([icon,title,context,x,y,values,linear])=>({icon,title,context,x,y,values,linear:!!linear}))
const P={l:54,r:22,t:24,b:44},clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),ease=t=>t<.5?2*t*t:1-Math.pow(-2*t+2,2)/2

export default function LinearVsNonlinear(){
 const canvas=useRef(),wrap=useRef(),raf=useRef(),timer=useRef(),map=useRef({})
 const [round,setRound]=useState(0),[width,setWidth]=useState(720),[shown,setShown]=useState(3),[phase,setPhase]=useState('guess'),[guess,setGuess]=useState(null),[moving,setMoving]=useState(null),[feedback,setFeedback]=useState('Tap the purple column to place your prediction.')
 const s=rounds[round],done=shown===6
 const maxY=useMemo(()=>{const m=Math.max(...s.values),step=m<=40?5:m<=100?10:25;return Math.ceil(m*1.08/step)*step},[s])
 useEffect(()=>{const ro=new ResizeObserver(([e])=>setWidth(Math.max(300,Math.floor(e.contentRect.width))));ro.observe(wrap.current);return()=>ro.disconnect()},[])
 useEffect(()=>()=>{cancelAnimationFrame(raf.current);clearTimeout(timer.current)},[])
 const reset=useCallback(i=>{cancelAnimationFrame(raf.current);clearTimeout(timer.current);setRound(i);setShown(3);setPhase('guess');setGuess(null);setMoving(null);setFeedback('Tap the purple column to place your prediction.')},[])
 const draw=useCallback(()=>{const el=canvas.current;if(!el)return;const h=210,dpr=devicePixelRatio||1;el.width=width*dpr;el.height=h*dpr;el.style.width=width+'px';el.style.height=h+'px';const c=el.getContext('2d');c.setTransform(dpr,0,0,dpr,0,0);c.clearRect(0,0,width,h);const pw=width-P.l-P.r,ph=h-P.t-P.b,x=i=>P.l+i/5*pw,y=v=>P.t+(1-v/maxY)*ph;map.current={x,ph};c.fillStyle='#fff';c.fillRect(0,0,width,h)
  if(shown<6){const tx=x(shown),col=pw/5;c.fillStyle=C.purpleTint;c.fillRect(tx-col*.43,P.t,col*.86,ph);c.strokeStyle=C.purple;c.setLineDash([6,5]);c.beginPath();c.moveTo(tx,P.t);c.lineTo(tx,h-P.b);c.stroke();c.setLineDash([])}
  c.font='600 11px Inter,system-ui';c.fillStyle=C.muted;c.textAlign='right';c.textBaseline='middle';for(let i=0;i<=4;i++){const v=maxY*i/4,yy=y(v);c.strokeStyle='#E7E3DC';c.lineWidth=1;c.beginPath();c.moveTo(P.l,yy);c.lineTo(width-P.r,yy);c.stroke();c.fillText(String(v),P.l-8,yy)}c.strokeStyle='#817E78';c.beginPath();c.moveTo(P.l,P.t);c.lineTo(P.l,h-P.b);c.lineTo(width-P.r,h-P.b);c.stroke();c.textAlign='center';c.textBaseline='top';for(let i=0;i<6;i++)c.fillText(String(i+1),x(i),h-P.b+8);c.fillText(s.x,width/2,h-16);c.save();c.translate(13,h/2);c.rotate(-Math.PI/2);c.fillText(s.y,0,0);c.restore()
  const pts=[];for(let i=0;i<shown;i++)pts.push([x(i),y(s.values[i])]);if(phase==='animating'&&moving!==null)pts.push([x(shown),y(moving)]);for(let i=1;i<pts.length;i++){c.strokeStyle=i<3?C.teal:C.orange;c.lineWidth=3;c.lineJoin='round';c.beginPath();c.moveTo(...pts[i-1]);c.lineTo(...pts[i]);c.stroke()}pts.forEach((p,i)=>{c.beginPath();c.arc(p[0],p[1],6,0,Math.PI*2);c.fillStyle=i<3?C.teal:C.orange;c.fill();c.strokeStyle='#fff';c.lineWidth=2;c.stroke()})
  if(guess!==null&&shown<6){const xx=x(shown),yy=y(guess);c.strokeStyle=C.purple;c.lineWidth=2;c.setLineDash([4,3]);c.beginPath();c.arc(xx,yy,8,0,Math.PI*2);c.stroke();c.setLineDash([]);c.fillStyle=C.purple;c.font='700 12px Inter,system-ui';c.textAlign=xx>width-100?'right':'left';c.textBaseline='bottom';c.fillText(`your guess: ${guess}`,xx+(xx>width-100?-12:12),yy-7)}
 },[width,maxY,s,shown,phase,moving,guess]);useEffect(draw,[draw])
 const reveal=useCallback(g=>{const actual=s.values[shown],start=performance.now();setPhase('animating');setMoving(g);const tick=now=>{const t=clamp((now-start)/700,0,1);setMoving(g+(actual-g)*ease(t));if(t<1)raf.current=requestAnimationFrame(tick);else{const close=Math.abs(actual-g)<=maxY*.06;setShown(n=>n+1);setMoving(null);setGuess(null);setFeedback(close?`🎯 Great guess — actual value: ${actual}`:`The point landed at ${actual} — ${actual>g?'higher':'lower'} than your guess of ${g}!`);setPhase(shown+1===6?'done':'guess')}};raf.current=requestAnimationFrame(tick)},[s,shown,maxY])
 const tap=e=>{if(phase!=='guess'||done)return;e.preventDefault();const r=canvas.current.getBoundingClientRect(),lx=(e.clientX-r.left)*width/r.width,ly=(e.clientY-r.top)*210/r.height,{x,ph}=map.current,col=(width-P.l-P.r)/5;if(Math.abs(lx-x(shown))>col*.48||ly<P.t||ly>210-P.b)return;const snap=maxY<=40?1:5,g=clamp(Math.round(((1-(ly-P.t)/ph)*maxY)/snap)*snap,0,maxY);setGuess(g);setFeedback('Prediction locked in… watch where the real point lands!');clearTimeout(timer.current);timer.current=setTimeout(()=>reveal(g),600)}
 const first=s.values[1]-s.values[0],changes=s.values.slice(1,shown).map((v,i)=>v-s.values[i]);const hint=done?(s.linear?'Equal steps in x, same change in y every time → linear. Just keep adding the same amount.':'The change in y is different each step → non-linear. Curves defy straight-line prediction — the change itself keeps changing.'):(shown===3?'Look at the change between the first points. If it stays the same, the pattern continues in a straight line — use that to predict!':'Check the chips: green = same change as before, rose = the change is changing. Let them guide your next guess.')
 return <div className="lvn" style={{background:C.page,color:C.ink}}><style>{`.lvn{height:500px;overflow:hidden;padding:8px 12px;font-family:Inter,system-ui}.lvn *{box-sizing:border-box}.lvn-card{background:#fff;border:.5px solid ${C.border};border-radius:12px}.lvn-top{height:47px;display:flex;align-items:center;gap:10px;padding:6px 12px}.lvn-icon{font-size:24px}.lvn-title{font-size:14px;font-weight:800}.lvn-sub,.lvn-progress{font-size:11px;color:${C.muted};margin-top:1px}.lvn-progress{margin-left:auto;font-weight:700}.lvn-task{height:30px;margin:6px 0;padding:6px 12px;background:${C.purpleTint};color:${C.purple};font-size:12px;font-weight:800;border-left:4px solid ${C.purple};border-radius:8px}.lvn-graph{overflow:hidden}.lvn canvas{display:block;width:100%;touch-action:none;cursor:crosshair}.lvn-status{height:30px;padding:6px 10px;font-size:12px;font-weight:700;text-align:center}.lvn-chips{display:flex;align-items:center;gap:6px;height:34px;overflow-x:auto;padding:5px 0}.lvn-chip{flex:none;border-radius:999px;padding:4px 8px;font-size:11px;font-weight:800;animation:chip .35s cubic-bezier(.2,1.6,.4,1)}@keyframes chip{from{transform:scale(.45);opacity:0}}.lvn-verdict{height:48px;overflow:hidden;padding:7px 11px;font-size:11px;line-height:1.25}.lvn-verdict strong{font-size:12px}.lvn-bottom{height:43px;display:flex;gap:8px;align-items:stretch;margin-top:6px}.lvn-hint{flex:1;overflow:hidden;padding:6px 10px;font-size:11px;line-height:1.25}.lvn-btn{border:0;border-radius:9px;padding:6px 12px;background:${C.teal};color:#fff;font-size:12px;font-weight:800;cursor:pointer}`}</style>
 <section className="lvn-card lvn-top"><div className="lvn-icon">{s.icon}</div><div><div className="lvn-title">{s.title}</div><div className="lvn-sub">{s.context}</div></div><div className="lvn-progress">Round {round+1} of 6</div></section><div className="lvn-task">Predict point {shown+1}: tap inside the purple column.</div>
 <section ref={wrap} className="lvn-card lvn-graph"><canvas ref={canvas} onPointerDown={tap} onTouchStart={e=>e.preventDefault()} role="img" aria-label={`Graph of ${s.title}. ${shown} of 6 points revealed.`}/><div className="lvn-status" style={{color:feedback.startsWith('🎯')?C.green:feedback.startsWith('The point')?C.rose:C.purple}} aria-live="polite">{feedback}</div></section>
 <div className="lvn-chips"><strong style={{fontSize:12}}>Changes:</strong>{changes.map((d,i)=>{const same=d===first;return <span key={i} className="lvn-chip" style={{color:same?C.green:C.rose,background:same?C.greenTint:C.roseTint}}>{d>=0?'+':''}{d} {same?'• same':'• changed'}</span>})}</div>
 {done&&<section className="lvn-card lvn-verdict" style={{background:s.linear?C.greenTint:C.roseTint,color:s.linear?C.green:C.rose}}>{s.linear?<><strong>Linear — totally predictable.</strong> Every step changed by the same amount ({first>=0?'+':''}{first}), so the line stayed straight and your guesses could follow the pattern.</>:<><strong>Non-linear — it kept surprising you.</strong> The change grew every step ({changes.map(d=>`${d>=0?'+':''}${d}`).join(', ')}) — a changing rate bends the graph into a <strong>curve</strong> that outruns straight-line guessing.</>}</section>}
 <div className="lvn-bottom"><div className="lvn-card lvn-hint">💡 {hint}</div><button className="lvn-btn" type="button" onClick={()=>reset((round+1)%rounds.length)}>{done?'New relationship':'Skip relationship'} →</button></div></div>
}
